package at.fhtw.webenprjbackend.entity;
// TODO: Consider switching to OffsetDateTime instead of LocalDateTime (storing timezone offset)
// TODO: Consider adding status - publish visibility, DRAFT / PUBLISHED
// TODO: Auditing (createdBy, modifiedBy) implementation
import java.time.LocalDateTime;
import java.util.UUID;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Study post entity for the Motivise micro-blogging platform.
 * Enables students to share study notes, ask questions, and collaborate.
 * 
 * @author Wii
 * @version 0.1
 *
 * @author jasmin
 * @version 0.2
 */
@Entity
@Table(name = "posts")
public class Post {

    /**
     * Unique identifier for the post.
     * Auto-generated by the database using AUTO_INCREMENT.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, length = 30)
    private String subject;

    /**
     * Main content of the study post.
     * 
     * This is where students write their study notes, questions, or insights.
     * Validation ensures posts are meaningful (min 5 chars) but not too long (max 500 chars)
     * to maintain the micro-blogging nature.
     */
    @Column(nullable = false, length = 500)
    private String content;

    @Column(name = "image_url", length = 500)
    private String imageUrl;

    /**
     * FK -> users.id
     *
     */
    @ManyToOne(optional = false) // TODO: cascade = CascadeType.PERSIST?
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Timestamp when the post was first created.
     * Automatically set by @PrePersist callback.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt; // TODO: Consider switching to OffsetDateTime instead of LocalDateTime (storing timezone offset)

    /**
     * Timestamp when the post was last modified.
     * Automatically updated by @PreUpdate callback when post is edited.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ===============================
    // Constructors
    // ===============================

    /**
     * Default constructor required by JPA.
     * Used by Hibernate when loading entities from database.
     */
    public Post() {}




    /**
     * Constructor for creating a new post with content and image an User info.
     * @param content The main text content of the post (required)
     *
     */
    public Post(String subject, String content, String imageUrl, User user) {
        this.subject = subject;
        this.content = content;
        this.imageUrl = imageUrl;
        this.user = user;
    }




    // ===============================
    // Getters and Setters
    // ===============================


    public UUID getId() {
        return id;
    }


    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    public LocalDateTime getCreatedAt() { return createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }

}
