package at.fhtw.webenprjbackend.entity;
// TODO: Consider switching to OffsetDateTime instead of LocalDateTime (storing timezone offset)
// TODO: Consider adding status - publish visibility, DRAFT / PUBLISHED
// TODO: Create a PostDto to avoid 'over-posting'
// TODO: Validation NOT HERE!!! -> Controller!
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Study post entity for the Motivise micro-blogging platform.
 * Enables students to share study notes, ask questions, and collaborate.
 * 
 * @author Wii
 * @version 0.1
 */
@Entity
@Table(name = "posts")
public class Post {

    /**
     * Unique identifier for the post.
     * Auto-generated by the database using AUTO_INCREMENT.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // TODO: Consider using UUIDs for better scalability
    private Long id;

    /**
     * Main content of the study post.
     * 
     * This is where students write their study notes, questions, or insights.
     * Validation ensures posts are meaningful (min 5 chars) but not too long (max 500 chars)
     * to maintain the micro-blogging nature.
     */
    @NotBlank(message = "Post content cannot be blank")
    @Size(min = 5, max = 500, message = "Post content must be between 5 and 500 characters")
    @Column(nullable = false, length = 500)
    private String content;

    /**
     * Optional title for the post.
     * 
     * Can be used for:
     * - Subject categorization (e.g., "Math - Derivatives")
     * - Question summaries (e.g., "Help with Spring Boot")
     * - Resource descriptions (e.g., "Great calculus video")
     */
    @Size(max = 100, message = "Title cannot exceed 100 characters")
    @Column(length = 100)
    private String title;

    /**
     * Timestamp when the post was first created.
     * Automatically set by @PrePersist callback.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the post was last modified.
     * Automatically updated by @PreUpdate callback when post is edited.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ===============================
    // Constructors
    // ===============================

    /**
     * Default constructor required by JPA.
     * Used by Hibernate when loading entities from database.
     */
    public Post() {}

    /**
     * Constructor for creating a new post with content and optional title.
     * 
     * @param content The main text content of the post (required)
     * @param title Optional title for categorization (can be null)
     */
    public Post(String content, String title) {
        this.content = content;
        this.title = title;
    }

    // ===============================
    // Getters and Setters
    // ===============================

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    // TODO: Consider removing setter to avoid accidental overrides or at least dont expose this
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    // TODO: Consider removing setter to avoid accidental overrides or at least dont expose this
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }

    // ===============================
    // JPA Lifecycle Callbacks
    // ===============================

    /**
     * Called automatically by JPA before persisting a new post to the database.
     * Sets the creation timestamp to current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    /**
     * Called automatically by JPA before updating an existing post in the database.
     * Updates the modification timestamp to current time.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
